target-version = "py312"  # 프로젝트의 Python 버전에 맞춤
line-length = 88
unsafe-fixes = true     # 자동 수정 허용
show-fixes = true       # 적용된 수정사항 표시

[lint]
select = ["E", "F", "I"]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"


[lint.isort]
# isort의 profile을 black으로 설정
force-single-line = false
force-wrap-aliases = false
combine-as-imports = true
known-first-party = ["notebooks"]
# 라인 길이 제한
lines-after-imports = 2
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

# Jupyter Notebook 관련 특별 설정
[lint.per-file-ignores]
"*.ipynb" = [
    "E402",   # 모듈 레벨 임포트가 코드 맨 위에 없어도 됨 (노트북 특성상)
    "F841",   # 할당 후 사용되지 않는 변수 무시
]
